#!/bin/sh
# https://bugs.launchpad.net/ubuntu/+source/isc-dhcp/+bug/1006937
/sbin/dhclient -cf /etc/tinc/core-vpn/dhclient.conf -nw -v  $INTERFACE -r
/sbin/dhclient -cf /etc/tinc/core-vpn/dhclient.conf -nw -v  $INTERFACE
